#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions
# RunFunctionsもシェルスクリプト．
# “.”コマンドで読み込むことでAllrunからRunFunction内のスクリプトが使用可能になる

runApplication blockMesh

restore0Dir

runApplication setFields

runApplication $(getApplication)